-- 코드를 입력하세요
(
    SELECT PT_NAME, PT_NO, GEND_CD, AGE, TLNO
    FROM PATIENT
    WHERE TLNO IS NOT NULL AND AGE < 13 AND GEND_CD = "W"
    UNION ALL
    SELECT PT_NAME, PT_NO, GEND_CD, AGE, "NONE" AS TLNO
    FROM PATIENT
    WHERE TLNO IS NULL AND AGE < 13 AND GEND_CD = "W"
)
ORDER BY AGE DESC, BINARY PT_NAME;
